### ISSUE TITLE
Using WalletLogin on Android Wrong Address

### ISSUE THREAD

**Issue by hankdangerfield** [ChainSafe/web3.unity#188]
**Describe the bug**
After signing a transaction in Metamask to login with Android APK, the address passed over to PlayerPrefs is incorrect.

**To Reproduce**
1. Use WalletLogin scene
2. Build to APK
3. Open APK
4. Click login
5. Chose metamask
6. Go to broswer
7. Sign
8. Go back to game
9. Player address is wrong
10. You may need to setup a text field that is updated to display the player account to UI

**Expected behavior**
A user's public address passed over to PlayerPrefs

**Smartphone (please complete the following information):**
 - Device: S22 Ultra
 - OS: Android 12
 - Browser Metamask

**Comment by KBryan** [comment]
Are you using the SignVerify Examples to do this? https://github.com/ChainSafe/web3.unity/blob/main/Web3Unity/Scripts/Prefabs/Wallet/SignVerifyWebWallet.cs

**Comment by sneakzttv** [comment]
Alot of users are having android 12 issues due to the way metamasks works, this may help hopefully.

[FIX] Fixes issues releated to deep/universal links by andreahaku ·...
"Open Android settings , search 'default' and select "Choose Default apps' > "Choose Default apps" > Opening Links > scroll down to MetaMask and tap it > Supported Web addresses > check if links are selected or "verified/trusted" by default (most importantly metamask.app.link). If they are not, then check them/it" 

This is all we have from our side regarding android 12 right now. Versions 9, 10 and 11 have no issues, we're waiting for metamask to update so we can fix any outstanding problems.

Closing this as resolved for now.
