### ISSUE TITLE
About obtaining information about NFT items owned by an account.

### ISSUE THREAD

**Issue by Hoget-Sato** [ChainSafe/web3.unity#655]
Hello :]
　
There currently a way to receive existing NFT items using Web3.Unity?
　
*To be exact, it would be ideal if players who logged in with METAMASK etc. could access all NFT items held by them.

When I read the script, I thought that AllErc721() in CSServer.cs might apply, but I'm having trouble because it doesn't work properly.

Unity version: 2022.2.19f1
Web3.Unity version: 2.5.0

**Comment by kalambet** [comment]
Hello @Hoget-Sato currently `AllErc721` is using corresponding API endpoint on our server.
We maintain an indexer behind this endpoint. Unfortunately this endpoint currently experiencing some problems. Mainly because supporting an index of all possible NFTs for all possible users on all supported networks is almost impossible task.

Essentially we will bring functionality to spin up own indexers, integrate them with SDK and make this request possible but for now I highly encourage you to setup either [The Graph](https://thegraph.com/) or the [Subsquid](https://subsquid.io/) indexer for the contracts you are interested in. Both of those products has free tiers.

**Comment by Hoget-Sato** [comment]
Thank you for your reply!
It was very easy to understand and helpful! :]

**Comment by Hoget-Sato** [comment]
Sorry, Please let me confirm just to be sure.

What I am currently trying to acquire is a horse NFT item from a game called METAHORSE by Adill Chain.
NFT data for this horse is currently unavailable.
That's what you mean, right?

**Comment by sneakzttv** [comment]
fixed in 2.5.1
