### ISSUE TITLE
Block Racers

### ISSUE THREAD

**Issue by boorich** [ChainSafe/web3.unity#724]
- [x] Upgrade graphics so that the game looks more polished (more post processing)
- [x] Integrate new SDK
- [x] #839
- [x] Decide on git flow
**Complete Demo**
- [x] https://github.com/ChainSafe/BlockBlasterz/issues/37

**Comment by sneakzttv** [comment]
Git flow complete: We can use unity's version control on the free tier but that only allows 3 of us to work on the project at once. Git will be simpler, we just need to be organized when it comes to tasks as clashes happen when people are working on the same scenes due to the meta files. As long as we're separating our tasks and staying to different scenes it will be fine.

**Comment by sneakzttv** [comment]
SDK integration complete, working with @RyRy79261 regarding contracts. As per Ry's contract iterations we're pivoting to Web3auth so this can be our flagship game for developers learning the protocol.

I still need to do some UI work after the contracts are integrated in terms of NFT population on screen as any NFT related work I do before the new contracts are in will be null and void.

**Comment by sneakzttv** [comment]
Continued in game repo:
https://github.com/ChainSafe/BlockRacers/issues/
