### ISSUE TITLE
Lootboxes not working if you have a Login scene

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#742]
**Describe the bug**
You can't use SampleLootboxes with a Login scene

**Steps**
1. Use the scene [SampleLogin or SampleLogin - Web3Auth]
2. Add the scene SampleLootboxes in Build settings
3. Remove the scene SampleMain from Build settings
4. Login with [Web3Auth or Remote wallet]
5. See error

**Expected behavior**
SampleLootboxes scene is displayed

**Console errors**
```
Scene 'SampleMain' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.
To add a scene to the build settings use the menu File->Build Settings...
```

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Unity Version: [e.g., 2022.1]
 - Operating System: [Mac]

**Additional context**
You can test lootboxes scene without the login scene and it works perfectly, this is a UX issue

**Comment by sneakzttv** [comment]
The above happens bc we set the scene transition to name rather than scene index as users may be placing the sdk into an already built game with scenes making the index useless. We could put a conditional in perhaps that checks which scenes exist, choose lootboxes first, if else choose main else choose the next scene index.
